apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins-container
          image: siddhant231xyz/myjenkins-blueocean:2.462.1-1
          ports:
            - containerPort: 8080
            - containerPort: 50000
